version: '0.6.{build}'

image: Visual Studio 2019

platform:
  - x64
  
install:
  - cinst ffmpeg
  
configuration:
  - Release
  - Debug

#build:
#  project: $(APPVEYOR_BUILD_FOLDER)\derperview.sln

before_build:
    - cmake -G "Visual Studio 16 2019" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

